better init script and no longer inlining nginx installation version

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -63,22 +63,42 @@
     set +eo pipefail
 
     ssh_keyfile="$DIR/.ssh_key"
+    connect_seconds_valid=5
+    connect_max_tries=10
+    connect_attempt=0
+    connected=''
 
     while :; do
-        set -x
-        install -m 0600 /dev/null "$ssh_keyfile"
-        docker exec -it -u vagrant:vagrant "$name" bash -c '(test -f "$HOME/.ssh/id_rsa" || ssh-keygen -t rsa -b 4096 -f "$HOME/.ssh/id_rsa" -q -N "" && install -m 0600 "$HOME/.ssh/id_rsa.pub" "$HOME/.ssh/authorized_keys") && cat "$HOME/.ssh/id_rsa"' >> "$ssh_keyfile"
-        set +x
-
-        ssh \
-            -i "$ssh_keyfile" \
-            -p "$local_ssh_port" \
-            -o IdentitiesOnly=yes \
-            -o PasswordAuthentication=no \
-            -o UserKnownHostsFile=/dev/null \
-            -o StrictHostKeyChecking=no \
-            $(test ! -s "$DIR/.ssh-options" || (cat "$DIR/.ssh-options" | sed -E 's/^\s*#.*$//' | tr '\n' ' ') ) \
-            vagrant@127.0.0.1
+        while :; do
+            connect_attempt=$(( $connect_attempt + 1 ))
+            if [[ $connect_attempt -gt $connect_max_tries ]]; then
+                connect_attempt=0
+                echo "Failed to connect after $connect_max_tries attempts, something is wrong"
+                break
+            fi
+            set -x
+            install -m 0600 /dev/null "$ssh_keyfile"
+            docker exec -it -u vagrant:vagrant "$name" bash -c '(test -f "$HOME/.ssh/id_rsa" || ssh-keygen -t rsa -b 4096 -f "$HOME/.ssh/id_rsa" -q -N "" && install -m 0600 "$HOME/.ssh/id_rsa.pub" "$HOME/.ssh/authorized_keys") && cat "$HOME/.ssh/id_rsa"' >> "$ssh_keyfile"
+            [ ! -s "$ssh_keyfile" ] && sleep 1 && continue
+            set +x
+            start_seconds="$SECONDS"
+            ssh \
+                -i "$ssh_keyfile" \
+                -p "$local_ssh_port" \
+                -o IdentitiesOnly=yes \
+                -o PasswordAuthentication=no \
+                -o UserKnownHostsFile=/dev/null \
+                -o StrictHostKeyChecking=no \
+                $(test ! -s "$DIR/.ssh-options" || (cat "$DIR/.ssh-options" | sed -E 's/^\s*#.*$//' | tr '\n' ' ') ) \
+                vagrant@127.0.0.1
+            seconds_elapsed=$(( $SECONDS - $start_seconds ))
+            if [[ $seconds_elapsed -ge $connect_seconds_valid ]]; then
+                connected='y'
+                connect_attempt=0
+            fi
+            [ -n "$connected" ] && break
+            [[ $seconds_elapsed -lt 1 ]] && sleep 1
+        done
 
         reset
         echo "$prompt"
